fs=100;
ts=1/fs;
t_start=0;
t_end=1;
T=t_end-t_start;
N = fs * T;
t = t_start:ts:t_end-ts;
f = -fs/2:fs/N:fs/2-fs/N;
fc=5;
alpha=0.5;
beta=0.3;
R=250000;
V=180/3.6;
fd=beta*V;
C=3e8;
Ro=2/C;
td=Ro*R;
x=alpha*cos(2*pi*(fc+fd)*(t-td));
plot(t,x);
title('Received signal');
xlabel('Time (s)');
ylabel 'x(t)';